# ServerTokens et ServerSignature doivent etre en global (hors VirtualHost)
ServerTokens Full
ServerSignature On

<VirtualHost *:80>
    DocumentRoot /var/www/html
    ServerName site-vulnerable

    <Directory /var/www/html>
        Options +Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <Location /server-status>
        SetHandler server-status
        Require all granted
    </Location>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
